[build]
  command = "yarn build"
  functions = "lambda"
  publish = "dist"

[dev]
  command = "yarn serve" # Command to start your dev server
  port = 3000 # Port that the dev server will be listening on
  functionsPort = 34567 # port for functions server
  autoLaunch = true